'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,ArrowDownLeft,Plus,Users,Receipt,Compass,Link as LinkIcon,Check,ArrowRight,Wallet,RefreshCw,Pencil,Trash2} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogAction,AlertDialogCancel,AlertDialogFooter} from '@/components/ui/alert-dialog';
import {Toaster,toast} from 'sonner';
import {Group,Expense,balances,transfers,split,cents} from '@/lib/ledger';
import {APP_HOME, API_PATH} from '@/lib/paths';
const money=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(n/100);
const today=()=>new Date().toLocaleDateString('en-CA');
function Pick({value,onChange,items}:{value:string;onChange:(v:string)=>void;items:{id:string;name:string}[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger className="pick"><SelectValue/></SelectTrigger><SelectContent>{items.map(m=><SelectItem key={m.id} value={m.id}>{m.name}</SelectItem>)}</SelectContent></Select>;}
function Avatar({name,index=0}:{name:string;index?:number}){return <span className={'avatar color'+index%5}>{name.slice(0,2).toUpperCase()}</span>;}
export default function Safari(){
const [g,setG]=useState<Group|null>(null),[me,setMe]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[modal,setModal]=useState(''),[tab,setTab]=useState('expenses');
const [userName,setUserName]=useState(''),[groupName,setGroupName]=useState(''),[names,setNames]=useState(''),[plannedContribution,setPlannedContribution]=useState(''),[newMember,setNewMember]=useState(''),[invite,setInvite]=useState(''),[inviteName,setInviteName]=useState('');
const [edit,setEdit]=useState<Expense|null>(null),[title,setTitle]=useState(''),[amount,setAmount]=useState(''),[payer,setPayer]=useState(''),[date,setDate]=useState(today()),[participants,setParticipants]=useState<string[]>([]),[mode,setMode]=useState('equal'),[values,setValues]=useState<Record<string,string>>({}),[remove,setRemove]=useState<Expense|null>(null),[payment,setPayment]=useState<{from:string;to:string;amount:number}|null>(null);
async function api(body?:unknown){const r=await fetch(API_PATH,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:undefined);const data=await r.json() as {group?:Group|null;me?:string;error?:string;token?:string};if(!r.ok)throw Error(data.error||'Please try again.');if('group'in data){setG(data.group||null);setMe(data.me||'');}return data;}
async function act(body:unknown,close=true){setBusy(true);setError('');try{const data=await api(body);if(close)setModal('');return data;}catch(e){setError((e as Error).message);throw e;}finally{setBusy(false);}}
useEffect(()=>{const token=new URLSearchParams(location.hash.slice(1)).get('invite');api(token?{action:'join',token}:undefined).then(()=>{if(token)history.replaceState(null,'',location.pathname);}).catch(e=>setError(e.message)).finally(()=>setLoading(false));},[]);
useEffect(()=>{if(!g)return;const timer=setInterval(()=>{if(document.visibilityState==='visible'&&!busy)api().catch(()=>{});},20000);return()=>clearInterval(timer);},[g?.id,busy]);
useEffect(()=>{const context=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();Promise.resolve(context.registerTool({name:'start_expense_creation',description:'Open the expense form for the current group. Does not save an expense.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:(input:unknown)=>{if(!g)throw Error('Create or join a group first.');if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('Expected an empty object.');openExpense();return {opened:true};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[g?.id,me]);
function openExpense(e?:Expense){setEdit(e||null);setTitle(e?.title||'');setAmount(e?String(e.amount/100):'');setPayer(e?.payer||me);setDate(e?.date||today());setParticipants(e?Object.keys(e.shares):g!.members.map(m=>m.id));setMode(e?'exact':'equal');setValues(e?Object.fromEntries(Object.entries(e.shares).map(([id,n])=>[id,String(n/100)])):{});setError('');setModal('expense');}
const b=g?balances(g):{},ts=g?transfers(g):[],myBalance=b[me]||0,total=g?.expenses.reduce((n,e)=>n+e.amount,0)||0,member=(id:string)=>g?.members.find(m=>m.id===id)?.name||'Participant';
let preview:Record<string,number>={};try{preview=split(cents(amount),participants,mode,values);}catch{}
const submit=(body:unknown,close=true)=>{void act(body,close).catch(()=>{});};
return <><Toaster position="top-center"/><header className="topbar"><a href={APP_HOME} className="brand"><span className="brand-icon"><Compass size={23}/></span>Split<span>Safari</span></a><div className="header-right"><span className="quiet">Shared expenses, sorted.</span>{g&&<span className="identity"><Avatar name={member(me)}/>{member(me)}</span>}</div></header>
{loading?<main className="onboard"><Compass className="spin"/><h1>Opening your space…</h1></main>:!g?<main className="welcome"><section className="welcome-copy"><span className="eyebrow">LESS MATH. MORE MEMORIES.</span><h1>Good times.<br/>Fair shares.</h1><p>Trips, dinners, and everything in between.<br/>Keep the money part simple.</p><div className="steps"><span><Users/>Add your people</span><span><Receipt/>Split what you share</span><span><Check/>Settle up together</span></div><div className="privacy-note"><LinkIcon size={18}/><p>No signup. Your group is accessible only through personal invite links.</p></div></section><section className="panel start-panel"><span className="tag">YOUR NEXT ADVENTURE</span><h2>Create your group</h2><p className="muted">Just your name, and you’re in.</p><form onSubmit={e=>{e.preventDefault();submit({action:'create',name:userName,groupName,plannedContribution,names:names.split(/[,\n]/).map(n=>n.trim()).filter(Boolean)});}}><label>Your name<input required maxLength={80} value={userName} onChange={e=>setUserName(e.target.value)} placeholder="e.g. Sourabh" autoComplete="given-name"/></label><label>Group name<input required maxLength={80} value={groupName} onChange={e=>setGroupName(e.target.value)} placeholder="e.g. Goa getaway"/></label><label>Who’s coming along? <span className="optional">Optional</span><textarea value={names} onChange={e=>setNames(e.target.value)} placeholder="Rahul, Priya, Amit" rows={3}/><small>Separate names with commas. They can join later.</small></label><label>Planned contribution per person (₹)<input inputMode="decimal" value={plannedContribution} onChange={e=>setPlannedContribution(e.target.value)} placeholder="Optional, e.g. 2000"/><small>A target only; this does not record money collected.</small></label>{error&&<p role="alert" className="error">{error}</p>}<button className="primary wide" disabled={busy}>{busy?'Creating…':'Create group'}<ArrowRight size={18}/></button><p className="footnote">Have an invite? Open the link your organiser shared.</p></form></section></main>:<main className="workspace"><div className="breadcrumb">Your group <span>/</span> {g.name}</div><section className="group-heading"><div><span className="eyebrow">A LITTLE LESS “WHO OWES WHO?”</span><h1>{g.name}</h1><p className="muted">{g.members.length} participants <span className="dot">·</span> INR <span className="dot">·</span> {g.members.filter(m=>m.connected).length} connected</p></div><div className="actions"><button className="secondary" onClick={()=>{setTab('people');}}><Users size={17}/>Participants</button><button className="primary" onClick={()=>openExpense()}><Plus size={18}/>Add expense</button></div></section>
<section className="stats"><article className="stat total"><span>GROUP SPENDING <Receipt size={18}/></span><strong>{money(total)}</strong><small>{g.expenses.length} shared expense{g.expenses.length===1?'':'s'}</small></article><article className="stat"><span>YOU ARE OWED <ArrowDownLeft size={20}/></span><strong className="positive">{money(Math.max(myBalance,0))}</strong><small>{myBalance>0?'Coming back your way':'Nothing to collect'}</small></article><article className="stat"><span>YOU OWE <ArrowUpRight size={20}/></span><strong>{money(Math.max(-myBalance,0))}</strong><small>{myBalance<0?'Your share to settle':'You’re all caught up'}</small></article></section>
{error&&!modal&&<p role="alert" className="error">{error} <button onClick={()=>api().then(()=>setError('')).catch(e=>setError(e.message))}>Retry</button></p>}
{g.plannedContribution!==undefined&&<section className="contribution-plan" aria-label="Contribution plan"><div><span className="eyebrow">CONTRIBUTION PLAN</span><h2>{money(g.plannedContribution)} <span>per person</span></h2><p>Planned only · No contributions recorded as collected</p></div><div><small>Group target · {g.members.length} people</small><strong>{money(g.plannedContribution*g.members.length)}</strong></div><div><small>{total>g.plannedContribution*g.members.length?'Over target':'Unspent target'}</small><strong className={total>g.plannedContribution*g.members.length?'negative':'positive'}>{money(Math.abs(g.plannedContribution*g.members.length-total))}</strong></div></section>}<div className="content-grid"><section className="panel ledger"><Tabs value={tab} onValueChange={setTab}><div className="tabbar"><TabsList variant="line"><TabsTrigger value="expenses">Expenses</TabsTrigger><TabsTrigger value="people">People</TabsTrigger><TabsTrigger value="activity">Activity</TabsTrigger></TabsList><button aria-label="Refresh group" className="icon-button" onClick={()=>api().then(()=>toast.success('Up to date')).catch(e=>setError(e.message))}><RefreshCw size={16}/></button></div>
<TabsContent value="expenses">{!g.expenses.length?<div className="empty"><span className="empty-icon"><Receipt size={28}/></span><h2>A fresh start</h2><p>Add your first shared expense.<br/>Choose exactly who’s part of the split.</p><button className="primary" onClick={()=>openExpense()}><Plus size={18}/>Add first expense</button></div>:<div className="expense-list">{g.expenses.map(e=><article className="expense" key={e.id}><div className="receipt-icon"><Receipt size={20}/></div><div className="expense-description"><h3>{e.title}</h3><p>{member(e.payer)} paid <span>·</span> {new Date(e.date+'T12:00:00').toLocaleDateString('en-IN',{day:'numeric',month:'short'})}</p><details><summary>Split between {Object.keys(e.shares).length} people</summary>{Object.entries(e.shares).map(([id,n])=><div className="share-line" key={id}>{member(id)}<span>{money(n)}</span></div>)}</details></div><div className="expense-amount"><strong>{money(e.amount)}</strong><small>{me in e.shares?`Your share ${money(e.shares[me])}`:'You’re not in this split'}</small>{e.author===me&&<div className="edit-actions"><button aria-label={'Edit '+e.title} onClick={()=>openExpense(e)}><Pencil size={14}/></button><button aria-label={'Delete '+e.title} onClick={()=>setRemove(e)}><Trash2 size={14}/></button></div>}</div></article>)}</div>}</TabsContent>
<TabsContent value="people"><div className="section-intro"><div><h2>Everyone’s included</h2><p className="muted">People can share expenses before they connect.</p></div>{me===g.owner&&<button className="secondary" onClick={()=>{setError('');setModal('member');}}><Plus size={16}/>Add</button>}</div>{g.members.map((m,i)=><div className="person-row" key={m.id}><Avatar name={m.name} index={i}/><div className="person-info"><strong>{m.name}{m.id===me?' (you)':''}</strong><small>{m.id===g.owner?'Organiser':m.connected?'Connected':'Not connected yet'}</small></div>{me===g.owner&&<button className="text-button" disabled={busy} onClick={async()=>{try{const r=await act({action:'invite',memberId:m.id},false);setInvite(location.origin+APP_HOME+'#invite='+r.token);setInviteName(m.name);setModal('invite');}catch{}}}><LinkIcon size={15}/>{m.id===me?'Recovery link':'Invite link'}</button>}</div>)}</TabsContent>
<TabsContent value="activity">{!g.activity.length?<div className="empty"><h2>All quiet here</h2><p>Your group’s expense and payment history will appear here.</p></div>:g.activity.map((a,i)=><div className="activity" key={i}><span className="activity-mark"/><div><p>{a.text}</p><small>{new Date(a.date).toLocaleString('en-IN')}</small></div></div>)}{g.settlements.length>0&&<div className="section-intro"><div><h2>Recorded payments</h2>{g.settlements.map(s=><p key={s.id}>{member(s.from)} → {member(s.to)} · {money(s.amount)}</p>)}</div></div>}</TabsContent></Tabs></section>
<aside><section className="panel balances"><div className="aside-title"><h2>Settle up</h2><Wallet size={19}/></div><p className="muted">Fewer payments. Same fair split.</p>{!ts.length?<div className="settled"><span><Check size={24}/></span><h3>All square</h3><p>No outstanding payments.</p></div>:ts.map((t,i)=><div className="transfer" key={i}><p><strong>{member(t.from)}</strong><ArrowRight size={15}/><strong>{member(t.to)}</strong></p><div><b>{money(t.amount)}</b>{[g.owner,t.from,t.to].includes(me)&&<button className="text-button" onClick={()=>{setPayment(t);setAmount(String(t.amount/100));setError('');setModal('settle');}}>Record payment</button>}</div></div>)}<p className="aside-note">Record payments made outside the app.</p></section><section className="group-balances"><h2>At a glance</h2>{g.members.map((m,i)=><div className="balance-row" key={m.id}><Avatar name={m.name} index={i}/><span>{m.name}</span><strong className={b[m.id]>0?'positive':b[m.id]<0?'negative':'muted'}>{b[m.id]===0?'Settled':(b[m.id]>0?'+':'−')+money(Math.abs(b[m.id]))}</strong></div>)}<small>Positive balances receive money; negative balances owe.</small></section></aside></div><footer>Made for shared moments. <span>Split fairly. Travel lightly.</span></footer></main>}
<Dialog open={!!modal} onOpenChange={open=>{if(!open&&!busy){setModal('');setError('');}}}><DialogContent className="safari-modal"><DialogTitle>{modal==='expense'?(edit?'Edit expense':'Add an expense'):modal==='member'?'Add a participant':modal==='invite'?`A personal link for ${inviteName}`:'Record a payment'}</DialogTitle><DialogDescription>{modal==='expense'?'Choose who paid and who shares this expense.':modal==='member'?'They’ll be included in calculations before joining.':modal==='invite'?'Anyone with this link can access the group as this person. Share it only with them.':'Use this after the payment has been made outside the app.'}</DialogDescription>
{modal==='expense'&&<form onSubmit={e=>{e.preventDefault();submit({action:'expense',id:edit?.id,title,amount,payer,date,participants,mode,values});}}><label>What was it for?<input required value={title} maxLength={80} onChange={e=>setTitle(e.target.value)} placeholder="Dinner, stay, taxi…"/></label><div className="form-grid"><label>Amount (₹)<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/></label><label>Date<input required type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div><label>Paid by<Pick value={payer} onChange={setPayer} items={g?.members||[]}/></label><label>Split method<Pick value={mode} onChange={setMode} items={[{id:'equal',name:'Equally'},{id:'exact',name:'Exact amounts'},{id:'percentage',name:'Percentages'}]}/></label><div className="split-heading"><strong>Split with</strong><button type="button" className="text-button" onClick={()=>setParticipants(participants.length===g?.members.length?[]:g!.members.map(m=>m.id))}>{participants.length===g?.members.length?'Clear':'Select all'}</button></div><div className="participants">{g?.members.map((m,i)=><div className="split-row" key={m.id}><Checkbox id={'split-'+m.id} checked={participants.includes(m.id)} onCheckedChange={checked=>setParticipants(checked?[...participants,m.id]:participants.filter(id=>id!==m.id))}/><label htmlFor={'split-'+m.id}>{m.name}</label>{participants.includes(m.id)&&(mode==='equal'?<small>{preview[m.id]!==undefined?money(preview[m.id]):'—'}</small>:<input aria-label={`${m.name} ${mode==='exact'?'amount':'percentage'}`} inputMode="decimal" placeholder={mode==='exact'?'₹ 0.00':'0%'} value={values[m.id]||''} onChange={e=>setValues({...values,[m.id]:e.target.value})}/>)}</div>)}</div><small className="muted">Only selected people share this expense.</small>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy} className="primary wide">{busy?'Saving…':edit?'Save changes':'Save expense'}</button></form>}
{modal==='member'&&<form onSubmit={e=>{e.preventDefault();submit({action:'member',name:newMember});setNewMember('');}}><label>Participant name<input required maxLength={80} value={newMember} onChange={e=>setNewMember(e.target.value)} placeholder="Their name"/></label>{error&&<p role="alert" className="error">{error}</p>}<button className="primary wide" disabled={busy}>Add participant</button></form>}
{modal==='invite'&&<><input aria-label="Personal invite link" readOnly value={invite} onFocus={e=>e.target.select()}/><button className="primary" onClick={()=>navigator.clipboard.writeText(invite).then(()=>toast.success('Link copied')).catch(()=>toast.error('Select the link and copy it manually.'))}><LinkIcon size={17}/>Copy link</button></>}
{modal==='settle'&&payment&&<form onSubmit={e=>{e.preventDefault();submit({action:'settle',from:payment.from,to:payment.to,amount});}}><p className="payment-label">{member(payment.from)} → {member(payment.to)}</p><label>Amount paid (₹)<input required inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/><small>Outstanding: {money(payment.amount)}. Partial payments are welcome.</small></label>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy} className="primary wide">Record payment</button></form>}
</DialogContent></Dialog>
<AlertDialog open={!!remove} onOpenChange={o=>{if(!o)setRemove(null);}}><AlertDialogContent><AlertDialogTitle>Delete “{remove?.title}”?</AlertDialogTitle><AlertDialogDescription>Its shares will be removed and everyone’s balances recalculated. This cannot be undone.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Keep expense</AlertDialogCancel><AlertDialogAction onClick={()=>submit({action:'delete',id:remove?.id})}>Delete expense</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}

