import { getDatabase } from '@/db/sqlite';
import { APP_BASE_PATH } from '@/lib/paths';
export const runtime = 'nodejs';
import { Group,cents,split,transfers } from '@/lib/ledger';
export const dynamic='force-dynamic';
const secret=()=>crypto.randomUUID()+crypto.randomUUID();
const hash=async(s:string)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');
const db=getDatabase;
const attempts=new Map<string,{count:number;reset:number}>();
const json=(data:unknown,status=200)=>Response.json(data,{status,headers:{'Cache-Control':'no-store','Referrer-Policy':'no-referrer'}});
const name=(v:unknown)=>{if(typeof v!=='string'||!v.trim()||v.trim().length>80)throw Error('Use a name between 1 and 80 characters.');return v.trim();};
async function identity(req:Request){const token=(req.headers.get('cookie')||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('splitsafari='))?.slice('splitsafari='.length);if(!token)return null;const cutoff=new Date(Date.now()-180*86400000).toISOString();return await db().prepare('SELECT * FROM sessions WHERE token = ? AND created_at >= ?').bind(await hash(token),cutoff).first<{group_id:string;member_id:string}>();}
async function read(id:string){const r=await db().prepare('SELECT data, version FROM groups WHERE id = ?').bind(id).first<{data:string;version:number}>();if(!r)throw Error('This group could not be found.');return {g:JSON.parse(r.data) as Group,version:r.version};}
async function session(groupId:string,memberId:string,req:Request){const token=secret();await db().prepare('INSERT INTO sessions (token,group_id,member_id,created_at) VALUES (?,?,?,?)').bind(await hash(token),groupId,memberId,new Date().toISOString()).run();return `splitsafari=${token}; HttpOnly; SameSite=Lax; Path=${APP_BASE_PATH}; Max-Age=15552000${(process.env.NODE_ENV==='production'||new URL(req.url).protocol==='https:')?'; Secure':''}`;}
export async function GET(req:Request){try{const who=await identity(req);if(!who)return json({group:null});return json({group:(await read(who.group_id)).g,me:who.member_id});}catch(e){console.error(e);return json({error:'Unable to load your group. Please try again.'},503);}}
export async function POST(req:Request){try{if(req.headers.get('origin')&&new URL(req.headers.get('origin')!).host!==req.headers.get('host'))return json({error:'Invalid request origin.'},403);if(req.headers.get('sec-fetch-site')==='cross-site')return json({error:'Cross-site requests are not allowed.'},403);if(req.headers.get('content-type')?.split(';')[0]!=='application/json')return json({error:'Send this request as JSON.'},415);if(Number(req.headers.get('content-length')||0)>50000)return json({error:'Request too large.'},413);const raw=await req.text();if(new TextEncoder().encode(raw).length>50000)return json({error:'Request too large.'},413);const b=JSON.parse(raw);const ip=req.headers.get('x-forwarded-for')?.split(',')[0]?.trim()||'local',key=`${ip}:${b.action==='create'||b.action==='join'?b.action:'write'}`,now=Date.now(),entry=attempts.get(key);if(!entry||entry.reset<=now)attempts.set(key,{count:1,reset:now+60000});else if(++entry.count>(b.action==='create'||b.action==='join'?20:120))return json({error:'Too many requests. Please wait a minute.'},429);
if(b.action==='create'){const id=crypto.randomUUID(),owner=crypto.randomUUID();if(!Array.isArray(b.names)||b.names.length>49)throw Error('A group supports up to 50 people.');const g:Group={id,name:name(b.groupName),plannedContribution:b.plannedContribution?cents(b.plannedContribution):undefined,owner,members:[{id:owner,name:name(b.name),connected:true},...b.names.map((n:unknown)=>({id:crypto.randomUUID(),name:name(n),connected:false}))],expenses:[],settlements:[],activity:[]};await db().prepare('INSERT INTO groups (id,name,data,version) VALUES (?,?,?,0)').bind(id,g.name,JSON.stringify(g)).run();const response=json({group:g,me:owner});response.headers.set('Set-Cookie',await session(id,owner,req));return response;}
if(b.action==='join'){if(typeof b.token!=='string'||b.token.length>150)throw Error('Invalid invitation.');const invite=await db().prepare('SELECT * FROM invites WHERE token = ?').bind(await hash(b.token)).first<{group_id:string;member_id:string}>();if(!invite)throw Error('This invitation is invalid. Ask the organiser for a new link.');for(let attempt=0;attempt<3;attempt++){const {g,version}=await read(invite.group_id);const m=g.members.find(m=>m.id===invite.member_id);if(!m)throw Error('Participant not found.');m.connected=true;const r=await db().prepare('UPDATE groups SET data = ?, version = version + 1 WHERE id = ? AND version = ?').bind(JSON.stringify(g),g.id,version).run();if(r.meta.changes){const response=json({group:g,me:m.id});response.headers.set('Set-Cookie',await session(g.id,m.id,req));return response;}}throw Error('The group changed. Please open the invitation again.');}
const who=await identity(req);if(!who)return json({error:'Open your personal invite link to access this group.'},401);const {g,version}=await read(who.group_id);const me=g.members.find(m=>m.id===who.member_id)!;
if(b.action==='invite'){if(me.id!==g.owner)return json({error:'Only the organiser can create invitations.'},403);if(typeof b.memberId!=='string'||!g.members.some(m=>m.id===b.memberId))throw Error('Participant not found.');const token=secret();await db().prepare('DELETE FROM invites WHERE group_id = ? AND member_id = ?').bind(g.id,b.memberId).run();await db().prepare('INSERT INTO invites (token,group_id,member_id,created_at) VALUES (?,?,?,?)').bind(await hash(token),g.id,b.memberId,new Date().toISOString()).run();return json({token});}
let activity='';if(b.action==='member'){if(me.id!==g.owner)return json({error:'Only the organiser can add participants.'},403);if(g.members.length>=50)throw Error('A group supports up to 50 people.');const n=name(b.name);g.members.push({id:crypto.randomUUID(),name:n,connected:false});activity=`${me.name} added ${n}`;}
else if(b.action==='expense'){if(g.expenses.length>=2000)throw Error('This group has reached its expense limit.');const amount=cents(b.amount);if(!Array.isArray(b.participants)||!b.participants.every((id:string)=>g.members.some(m=>m.id===id))||!g.members.some(m=>m.id===b.payer))throw Error('Choose participants and a payer from this group.');if(!/^\d{4}-\d{2}-\d{2}$/.test(b.date)||Number.isNaN(Date.parse(b.date)))throw Error('Choose a valid date.');const old=g.expenses.find(e=>e.id===b.id);if(b.id&&!old)throw Error('Expense not found.');if(old&&old.author!==me.id)return json({error:'Only the person who added this expense can edit it.'},403);const e={id:old?.id||crypto.randomUUID(),title:name(b.title),amount,payer:b.payer,shares:split(amount,b.participants,b.mode,b.values),date:b.date,author:me.id,mode:b.mode};g.expenses=old?g.expenses.map(x=>x.id===old.id?e:x):[e,...g.expenses];activity=`${me.name} ${old?'updated':'added'} ${e.title}`;}
else if(b.action==='delete'){const e=g.expenses.find(e=>e.id===b.id);if(!e||e.author!==me.id)return json({error:'Only the person who added this expense can delete it.'},403);g.expenses=g.expenses.filter(x=>x.id!==e.id);activity=`${me.name} deleted ${e.title}`;}
else if(b.action==='settle'){const amount=cents(b.amount);const t=transfers(g).find(t=>t.from===b.from&&t.to===b.to);if(me.id!==g.owner&&me.id!==b.from&&me.id!==b.to)return json({error:'Only the people involved or organiser can record this payment.'},403);if(!t||amount>t.amount)throw Error('Payment exceeds the current outstanding amount. Refresh and try again.');g.settlements.unshift({id:crypto.randomUUID(),from:b.from,to:b.to,amount,date:new Date().toISOString()});activity=`${me.name} recorded a payment`;}
else throw Error('Unknown action.');g.activity.unshift({text:activity,date:new Date().toISOString()});g.activity=g.activity.slice(0,200);const result=await db().prepare('UPDATE groups SET data = ?, version = version + 1 WHERE id = ? AND version = ?').bind(JSON.stringify(g),g.id,version).run();if(!result.meta.changes)return json({error:'Someone just updated the group. Refresh and try again.'},409);return json({group:g,me:me.id});
}catch(e){if(e instanceof SyntaxError)return json({error:'Invalid JSON.'},400);console.error('SplitSafari request failed',e instanceof Error?e.name:'Unknown error');return json({error:e instanceof Error?e.message:'Could not save. Please try again.'},400);}}

